image:
  # set up tcpdump so we don't have to install it manually
  file: .gitpod.Dockerfile

tasks:
  - name: shuffle up the concurrent connection values and start the containers
    before: shuf .env.suspects > .env.suspects.tmp && mv .env.suspects.tmp .env.suspects
    init: ./randomize_suspects.sh
    command: docker-compose --env-file .env.suspects up --build

ports:
  # we'll use this to check how quickly the website loads
  - port: 3000
    onOpen: open-preview
