image:
  # set up tcpdump so we don't have to install it manually
  file: .gitpod.Dockerfile

tasks:
  - name: start the containers
    init: ./randomize_suspects.sh
    command: docker-compose --env-file .env.suspects up --build
  - name: tcpdump investigation
    init: until (curl --head -s localhost:3000 > /dev/null); do sleep 1; clear; echo "Waiting for the containers to start up...when they're ready, the browser window will open above..."; done
    command: echo "let's start the investigation!"
    openMode: tab-after
  - name: delete the evidence
    command: sleep 5 && rm .env.suspects && exit

ports:
  # we'll use this to check how quickly the website loads
  - port: 3000
    onOpen: open-preview
